services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      

  backend:
    build: .
    ports:
      - "3000:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=myapp;Username=myuser;Password=mypassword"
    depends_on:
      - postgres

volumes:
  postgres_data: